// Simple API debug test
// Let's create a minimal API endpoint to test database connection

console.log("🔍 API Debug Test");
console.log("================");
console.log();
console.log("Since database is correct but API crashes, let's create a simple test.");
console.log();
console.log("🎯 Add this test endpoint to server/routes.ts:");
console.log();
console.log("// Test endpoint - add this to routes.ts");
console.log("app.get('/api/test', async (req, res) => {");
console.log("  try {");
console.log("    const { supabase } = require('./lib/supabase');");
console.log("    const { data, error } = await supabase");
console.log("      .from('users')");
console.log("      .select('email, spins_remaining, total_spins_used')");
console.log("      .limit(1);");
console.log("    ");
console.log("    if (error) {");
console.log("      console.error('Database error:', error);");
console.log("      return res.status(500).json({ error: error.message });");
console.log("    }");
console.log("    ");
console.log("    res.json({");
console.log("      message: 'Database connection working!',");
console.log("      data: data");
console.log("    });");
console.log("  } catch (err) {");
console.log("    console.error('Server error:', err);");
console.log("    res.status(500).json({ error: err.message });");
console.log("  }");
console.log("});");
console.log();
console.log("🧪 Test this endpoint:");
console.log("curl https://gptjewels.vercel.app/api/test");
console.log();
console.log("📋 What this will tell us:");
console.log("- If it works → Database connection is fine");
console.log("- If it crashes → Supabase connection issue");
console.log("- The error message will show exactly what's wrong");
console.log();
console.log("🚀 Deploy this test endpoint and then:");
console.log("1. Test /api/test");
console.log("2. Check Vercel logs for errors");
console.log("3. Identify the exact cause of the crash");
console.log();
console.log("💡 Most likely causes:");
console.log("- Supabase connection strings in Vercel");
console.log("- Import/export issues in serverless functions");
console.log("- Environment variable access issues");